CREATE DATABASE QUANLYTRUONGHOC
GO
USE QUANLYTRUONGHOC
GO

CREATE TABLE CHUCVU(
    MACV INT PRIMARY KEY ,
    TENCV NVARCHAR(100),
    TRANGTHAI BIT
)
CREATE TABLE PHONGBAN(
    MAPB INT PRIMARY KEY ,
    TENPB NVARCHAR(100) NOT NULL ,
    DIADIEM NVARCHAR(100),
    TRANGTHAI BIT
)
CREATE TABLE CANBO_VIENCHUC(
    MACB INT PRIMARY KEY ,
    HO nvarchar(20) NOT NULL,
	TENLOT nvarchar(50) NOT NULL,
	TEN nvarchar(20) NOT NULL,
	NGAYSINH date,
	DIACHI nvarchar(100),
	QUEQUAN NVARCHAR(100),
	NGAYBATDAU DATE,
	MAPB INT FOREIGN KEY REFERENCES PHONGBAN(MAPB),
	MACV INT FOREIGN KEY REFERENCES  CHUCVU(MACV),
	MACB_QUANLY INT FOREIGN KEY REFERENCES CANBO_VIENCHUC(MACB),
    TRANGTHAI BIT ,

)
CREATE TABLE KHOA_BOMON(
    MAKHOA_BOMON INT PRIMARY KEY ,
    TENKHOA_BOMON NVARCHAR(100) NOT NULL,
    DIADIEM NVARCHAR(100),
    MAKHOA_BOMONCHA INT FOREIGN KEY REFERENCES KHOA_BOMON(MAKHOA_BOMON),
    TRANGTHAI BIT
)
CREATE TABLE GIAOVIEN(
    MASOGV VARCHAR(8) PRIMARY KEY ,
    HO nvarchar(20) NOT NULL,
	TENLOT nvarchar(50) NOT NULL,
	TEN nvarchar(20) NOT NULL,
	NGAYSINH date,
	DIACHI nvarchar(100),
	LUONG INT,
	NGAYBATDAU DATE,
	MAKHOA_BOMON INT FOREIGN KEY REFERENCES KHOA_BOMON(MAKHOA_BOMON),
	MACV INT FOREIGN KEY REFERENCES CHUCVU(MACV),
	TRANGTHAI BIT
)
CREATE TABLE LOAIMONHOC(
    MALOAIMONHOC INT PRIMARY KEY ,
    TENLOAIMONHOC NVARCHAR(100),
    TRANGTHAI BIT
)
CREATE TABLE MONHOC(
	MAMONHOC INT PRIMARY KEY ,
    TENMON NVARCHAR(50),
    SOTINCHI INT,
    HESO FLOAT,
	HOCKY INT,
	MALOAIMONHOC INT FOREIGN KEY REFERENCES LOAIMONHOC(MALOAIMONHOC),
	MAKHOA_BOMON INT,
	TRANGTHAI BIT
)
CREATE TABLE PHANCONGGIANGDAY(
    MAMONHOC INT FOREIGN KEY REFERENCES MONHOC(MAMONHOC),
    MASOGV VARCHAR(8) FOREIGN KEY REFERENCES GIAOVIEN(MASOGV),
    NAMHOC INT,
    CONSTRAINT PK_PHANCONGGIANGDAY PRIMARY KEY (MAMONHOC, MASOGV, NAMHOC)
)
CREATE TABLE DANHSACHSINHVIEN(
    MASV INT PRIMARY KEY ,
    HO nvarchar(20) NOT NULL,
	TENLOT nvarchar(50) NOT NULL,
	TEN nvarchar(20) NOT NULL,
	NGAYSINH DATE,
	QUEQUAN NVARCHAR(100),
	DIACHI NVARCHAR(100),
	MAKHOA_BOMON INT FOREIGN KEY REFERENCES KHOA_BOMON(MAKHOA_BOMON),
	TRANGTHAI BIT
)
CREATE TABLE KETQUAHOCTAP(
   MAMONHOC INT FOREIGN KEY REFERENCES MONHOC(MAMONHOC),
    MASV INT FOREIGN KEY REFERENCES DANHSACHSINHVIEN(MASV),
    DIEMCHUYENCAN FLOAT,
    DIEMTBKIEMTRA FLOAT,
    DIEMTHI INT,
    DIEMTB FLOAT,
    CONSTRAINT PK_KETQUAHOCTAP PRIMARY KEY (MAMONHOC, MASV)
)



