CREATE DATABASE QUANLYTRUONGHOC
GO
USE QUANLYTRUONGHOC
GO

CREATE TABLE DIADIEMPHONG(
    MAPHONG INT ,
    DIADIEM NVARCHAR(100),
    CONSTRAINT PK_DIADIEMPHONG PRIMARY KEY (MAPHONG, DIADIEM)
)
CREATE TABLE PHONGBAN(
    MAPHONG INT PRIMARY KEY ,
    TENPHONG NVARCHAR(100) NOT NULL ,
    MANV_CANBO INT,
)
CREATE TABLE CANBO_VIENCHUC(
    MASO INT PRIMARY KEY ,
    HO nvarchar(20) NOT NULL,
	TENLOT nvarchar(50) NOT NULL,
	TEN nvarchar(20) NOT NULL,
	NGAYSINH date,
	DIACHI nvarchar(100),
	CHUCVU NVARCHAR(100),
	MACB_QUANLY INT,
    MAPHONG INT
)
CREATE TABLE KHOA(
    MAKHOA INT PRIMARY KEY ,
    TENKHOA NVARCHAR(100) NOT NULL,
    DIADIEM NVARCHAR(100),
    MAPHONG INT
)
CREATE TABLE BOMON(
    MAKHOA INT,
    STTMON INT,
    TENBOMON NVARCHAR(100),
	CONSTRAINT PK_CONGVIEC PRIMARY KEY (MAKHOA, STTMON)
)
CREATE TABLE DANHSACHSINHVIEN(
    MASV INT,
    MAKHOA INT,
    STTMON INT,
    HO nvarchar(20) NOT NULL,
	TENLOT nvarchar(50) NOT NULL,
	TEN nvarchar(20) NOT NULL,
	DIEMSO FLOAT,
	DIEMTRUNGBINH FLOAT,
	TRANGTHAI BIT,
	CONSTRAINT PK_DANHSACHSINHVIEN PRIMARY KEY (MASV, MAKHOA, STTMON)
)
CREATE TABLE GIAOVIEN(
    MASOGV VARCHAR(8),
	MAKHOA INT,
	STTMON INT,
    HO nvarchar(20) NOT NULL,
	TENLOT nvarchar(50) NOT NULL,
	TEN nvarchar(20) NOT NULL,
	NGAYSINH date,
	DIACHI nvarchar(100),
	CHUCVU NVARCHAR(100),
	LUONG INT,
	THAMNIEN INT,
	CONSTRAINT PK_GIAOVIEN PRIMARY KEY (MASOGV, MAKHOA, STTMON)
)

CREATE TABLE MONHOC(
	MAKHOA INT,
	STTMON INT,
    TENMON NVARCHAR(50),
	MASOGV VARCHAR(8),
    SOTINCHI INT,
    HESO FLOAT,
	HOCKY INT,
	THOIGIANDAY INT,
	MASV INT,
	NAMHOC INT,
	CONSTRAINT PK_MONHOC PRIMARY KEY (TENMON, MAKHOA, STTMON)
)
