CREATE DATABASE webtintuc;
GO

USE webtintuc;
GO

CREATE TABLE LOAITAIKHOAN(
    MALOAITK VARCHAR(10) PRIMARY KEY ,
    TENLOAITK NVARCHAR(50) NOT NULL
)
CREATE TABLE TAIKHOAN(
    TENTK VARCHAR(20) PRIMARY KEY ,
    MATKHAU VARCHAR(20) NOT NULL,
    HOTEN NVARCHAR(100),
    EMAIL NVARCHAR(100) NOT NULL,
    SDT VARCHAR(20),
    CMND VARCHAR(20),
    ANHDAIDIEN NVARCHAR(MAX),
    MALOAITK VARCHAR(10) FOREIGN KEY REFERENCES LOAITAIKHOAN(MALOAITK)
)
CREATE TABLE LOAITINTUC(
    MALOAITT VARCHAR(10) PRIMARY KEY ,
    TENLOAITT NVARCHAR(50) NOT NULL
)
CREATE TABLE TINTUC(
    MATT VARCHAR(10) PRIMARY KEY ,
    TIEUDE NVARCHAR(200) NOT NULL,
    TOMTAT NVARCHAR(MAX) NOT NULL,
    ANHDAIDIEN NVARCHAR(MAX) NOT NULL,
    NOIDUNG NVARCHAR(MAX) NOT NULL,
    NGAYDANG DATETIME NOT NULL,
    MALOAITT VARCHAR(10) FOREIGN KEY REFERENCES LOAITINTUC(MALOAITT),
    TENTK VARCHAR(20) FOREIGN KEY REFERENCES TAIKHOAN(TENTK),
    LUOTXEM INT
)
CREATE TABLE BINHLUAN(
    MABL VARCHAR(10) PRIMARY KEY ,
    NOIDUNG NVARCHAR(MAX) NOT NULL ,
    NGAYDANG DATETIME,
    TENTK VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES TAIKHOAN(TENTK),
    LUOTTHICH INT,
    MATT VARCHAR(10) FOREIGN KEY REFERENCES TINTUC(MATT)
)
CREATE TABLE ANHMINHHOA(
    MAANH VARCHAR(10) PRIMARY KEY ,
    DUONGDAN NVARCHAR(MAX) NOT NULL ,
    MOTA NVARCHAR(MAX),
    MATT VARCHAR(10) FOREIGN KEY REFERENCES TINTUC(MATT)
)